[package]
name = "easy-stitch"
version = "0.1.0"
authors = ["Kazurin Nanako <71819243+Kazurin-775@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.13"
structopt = "0.3.21"
